config/routes.rb
Rails.application.routes.draw do
  get 'teams/index'

  get 'teams/new'

  get 'teams/edit'

  get 'teams/show'

  get 'players/new'

  get 'session/new'

  get 'users/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'standings' => 'static_pages#standings'
  get 'bet-standings', to: 'static_pages#bets_standings', as: 'bet_standings'
  
  get 'signup'  => 'users#new'
  get 'players_new'  => 'players#new'
  get 'teams_new'  => 'teams#new'
  
  get '/users/:id/edit_admin_role', to: 'users#edit_admin_role', as: 'edit_admin_role_user'
  
  get '/players/:player_id/predictions/new', to: 'predictions#new', as: 'add_prediction_to_player'
  
  get '/players/:player_id/predictions', to: 'players#predictions', as: 'player_predictions'
  get '/players/:player_id/bets', to: 'players#bets', as: 'player_bets'
  
  get 'teams/standings', to: 'teams#standings', as: 'teams_standings'
  
  
  post 'teams/update_standings_ajax', to: 'teams#update_standings_ajax'
  post 'update_all_standings', to: 'static_pages#update_all_standings_ajax'

  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :users
  resources :players
  resources :teams
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :predictions

 

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                foreign_key: "follower_id",
                                dependent:   :destroy
                                
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
                                   
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  
  
  attr_accessor :remember_token
  before_save   :downcase_email
  
  mount_uploader :picture, PictureUploader

  
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_blank: true
  validate  :picture_size
  
  attr_accessor :remember_token
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  
  # Returns a user's status feed.
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end
  
  
    # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
  
  
  private
    def downcase_email
      self.email = email.downcase
    end
    
    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  
  before_action :admin_user,     only: [:destroy, :edit_admin_role, 
                                        :update_admin_role]
  
  before_action :admin_or_correct_user,   only: [:edit, :update]
  
  #before_action :correct_user,   only: [:edit, :update]
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the kladara!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def edit_admin_role
    @user = User.find(params[:id])
  end
  
  def update_admin_role
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Admin role updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :picture, :admin)
    end
    

 
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the avatar for the given user.
  def avatar_for(user, options = { })

    cs = options[:cs] || {:w => 40, :h => 40}
    size = options[:size] || 40
    ct = options[:ct] || false
    custom_size = options[:custom_size] || false
    
    if ct
      if custom_size
        if (user.picture?)
          string = 
          "<div class = 'avatar avatar-size-custom'"+
          "style = 'background-image:url(\"#{user.picture.url}\");" +
          "width:#{cs[:w]}px; height:#{cs[:h]}px;'></div>"
          return string.html_safe
               
        else
          string = 
          "<div class = 'avatar avatar-size-custom'"+
          "style = 'background-image:url(\"/uploads/user/picture/basic.png\");" +
          "width:#{cs[:w]}px; height:#{cs[:h]}px;'></div>"
          return string.html_safe
        end
        
      else
        if (user.picture?)
          string = 
          "<div class = 'avatar avatar-size-std'"+
          "style = 'background-image:url(\"#{user.picture.url}\")'></div>"
          return string.html_safe
               
        else
          string = 
          "<div class = 'avatar avatar-size-std'"+
          "style = 'background-image:url(\"/uploads/user/picture/basic.png\")'></div>"
          return string.html_safe
        end
      end
    
    else
      if (user.picture?)
        image_tag(user.picture.url, alt: user.name, 
          class: "logo avatar-size-#{size}" )
             
      else
        image_tag("/uploads/user/picture/basic.png", alt: user.name, 
          class: "avatar avatar-size-#{size}")
      end
    end
  end
 
 
  # Special avatar for header1
  def header_avatar_for(user, options = { size: 80 })

    if (user.picture?)
      image_tag(user.picture.url, alt: user.name, 
        class: "avatar header avatar-size-#{options[:size]}")
    else
      image_tag("/uploads/user/picture/basic.png", alt: user.name, 
        class: "avatar avatar-size-#{options[:size]}")
    end
  end
  
end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>

<%= f.label :email %>
<%= f.email_field :email, class: 'form-control' %>


<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>

<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation, class: 'form-control' %>

<span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
</span>
  
<script type="text/javascript">
  $('#user_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/users/_fields_admin_role.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>

<% if logged_in? && current_user.admin? && !current_user?(@user) %>
<%= f.label :admin %>
<%= f.check_box :admin, class: 'form-control-rb' %>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.
                          build(followed_id: @user.id),
                          remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<tr class = "user-row">
  <td>
    <%= avatar_for user,  size: 50, ct: true, 
                          custom_size: true, cs: {:w => 80, :h => 65} %>
  </td>
  
  <td>
    <div class="user-admin-text" >
                
      <div>
        <%= link_to user.name, user %>
   
      </div>
      <% if user.admin? %>
      <span class = "small-admin-notific">admin</span>
      <% end %>
    </div>
  </td>

  <td>
    <div><span><%= user.email %></span></div>

  </td>

  
  <% if current_user.admin? %>
    <td>
      <div><%= link_to "edit", edit_user_path(user) %></div>
      <div><%= link_to "edit_admin_role", edit_admin_role_user_path(user) %></div>
      <div>
        <% if !current_user?(user) %>
         
        <%= link_to "delete", user, method: :delete,
                                      data: { confirm: "You sure?" } %>
        <% end %>
      </div>
    </td>
  <% end %>

</tr>

app/views/users/edit.html.erb
<% provide(:title, "Edit user #{@user.name}") %>
<h1>Update profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, html: { multipart: true }) do |f| %>
      <div class="gravatar_edit">
        <%= avatar_for @user %>
      </div>
      <%= render 'fields', f: f %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>


  </div>
</div>

app/views/users/edit_admin_role.html.erb
<% provide(:title, "Edit admin role for #{@user.name}") %>
<h1>Update admin role</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, html: { multipart: true }) do |f| %>
      <%= render 'fields_admin_role', f: f %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>
<table class="users">
    <tr>
    <th>
      
    </th>
    <th>
      User
    </th>
    <th>
      Email
    </th>
    <% if current_user.admin? %>
    <th>
    </th>
    <% end %>
  </tr>
  <%= render @users %>
</table>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, html: { multipart: true }) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= avatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>