config/routes.rb
Rails.application.routes.draw do
  get 'teams/index'

  get 'teams/new'

  get 'teams/edit'

  get 'teams/show'

  get 'players/new'

  get 'session/new'

  get 'users/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'standings' => 'static_pages#standings'
  get 'bet-standings', to: 'static_pages#bets_standings', as: 'bet_standings'
  
  get 'signup'  => 'users#new'
  get 'players_new'  => 'players#new'
  get 'teams_new'  => 'teams#new'
  
  get '/users/:id/edit_admin_role', to: 'users#edit_admin_role', as: 'edit_admin_role_user'
  
  get '/players/:player_id/predictions/new', to: 'predictions#new', as: 'add_prediction_to_player'
  
  get '/players/:player_id/predictions', to: 'players#predictions', as: 'player_predictions'
  get '/players/:player_id/bets', to: 'players#bets', as: 'player_bets'
  
  get 'teams/standings', to: 'teams#standings', as: 'teams_standings'
  
  
  post 'teams/update_standings_ajax', to: 'teams#update_standings_ajax'
  post 'update_all_standings', to: 'static_pages#update_all_standings_ajax'

  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :users
  resources :players
  resources :teams
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :predictions

 

end

app/models/player.rb
class Player < ActiveRecord::Base
  
  has_many :predictions, dependent: :destroy, :inverse_of => :player
  
  mount_uploader :picture, PictureUploader

  
  validates :name,  presence: true, length: { maximum: 50 },
                    uniqueness: true

  validate  :picture_size
  
  
  
  private

    
    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :admin_user_confirm,     only: [:new, :edit, :update, :destroy]
  #before_action :update_players_points
  
  
  def index
    @players = Player.all
  end
  
  
  def show
    @player = Player.find(params[:id])
  end


  def new
    @player = Player.new
  end
  
  
  def destroy
    Player.find(params[:id]).destroy
    flash[:success] = "Player deleted"
    redirect_to players_url
  end
  
  
  def predictions
    @player = Player.find(params[:player_id])
    
    teams_east = @player.predictions.where("conference = ?", "east").order(:position)
    teams_west = @player.predictions.where("conference = ?", "west").order(:position)
 
    @player_predictions = {"East" => teams_east, "West" => teams_west}
  end
  
  
  def bets
    #update_standings
    predictions
  end
  
  
  def create
    @player = Player.new(player_params)
    if @player.save
      flash[:success] = "Player created!"
      redirect_to players_url
    else
      render 'new'
    end
  end
  
  
  def edit
    @player = Player.find(params[:id])
  end
  
  
  def update
    @player = Player.find(params[:id])
    if @player.update_attributes(player_params)
      flash[:success] = "Player updated"
      redirect_to player_url
    else
      render 'edit'
    end
  end


  private

    def player_params
      params.require(:player).permit(:name, :points, :picture)
    end
    
 
end

app/helpers/players_helper.rb
module PlayersHelper

  # Returns the avatar for the player
  def avatar_for_player(player, options = { })

    cs = options[:cs] || {:w => 40, :h => 40}
    size = options[:size] || 40
    ct = options[:ct] || false
    custom_size = options[:custom_size] || false
    
    if ct
      if custom_size
        if (player.picture?)
          string = 
          "<div class = 'avatar avatar-size-custom'"+
          "style = 'background-image:url(\"#{player.picture.url}\");" +
          "width:#{cs[:w]}px; height:#{cs[:h]}px;'></div>"
          return string.html_safe
               
        else
          string = 
          "<div class = 'avatar avatar-size-custom'"+
          "style = 'background-image:url(\"/uploads/user/picture/basic.png\");" +
          "width:#{cs[:w]}px; height:#{cs[:h]}px;'></div>"
          return string.html_safe
        end
        
      else
        if (player.picture?)
          string = 
          "<div class = 'avatar avatar-size-std'"+
          "style = 'background-image:url(\"#{player.picture.url}\")'></div>"
          return string.html_safe
               
        else
          string = 
          "<div class = 'avatar avatar-size-std'"+
          "style = 'background-image:url(\"/uploads/user/picture/basic.png\")'></div>"
          return string.html_safe
        end
      end
    
    else
      if (player.picture?)
        image_tag(player.picture.url, alt: player.name, 
          class: "logo avatar-size-#{size}" )
             
      else
        image_tag("/uploads/user/picture/basic.png", alt: player.name, 
          class: "avatar avatar-size-#{size}")
      end
    end
  end
 
  
end

app/views/players/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>


<%= f.label :points %>
<%= f.number_field :points, class: 'form-control' %>


<span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
</span>
  
<script type="text/javascript">
  $('#player_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/players/_player.html.erb
<tr class = "player-row">
  <td>
    <%= avatar_for_player player, size: 50, ct: true, 
                          custom_size: true, cs: {:w => 80, :h => 65}%>
  </td>
  
  <td>
    <div>
      <%= link_to player.name, player %>
    </div>
  </td>
  
  <td>
    <div >
      <span>points: <%=  player.points %></span>
    </div>
  </td>
  <td>
    <div><%= link_to "Bets", player_bets_path(player) %></div>
  </td>
  <td>
    <div><%= link_to "Predictions", player_predictions_path(player) %></div>
    <div><span><%= player.predictions.count %> predictions</span></div>
  </td>
  
  <% if current_user.admin? %>
  <td>
    <div><%= link_to "edit", edit_player_path(player) %></div>
    
    <div><%= link_to "delete", player, method: :delete,
                                  data: { confirm: "You sure?" } %></div>
  </td>
  <% end %>

</tr>

app/views/players/bets.html.erb
<%= render "predictions/player_bets" %>

app/views/players/edit.html.erb
<% provide(:title, "Edit player") %>
<h1>Update player</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@player, html: { multipart: true }) do |f| %>
      <div class="gravatar_edit">
        <%= avatar_for @player %>
      </div>
      <%= render 'fields', f: f %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    
  </div>
</div>

app/views/players/index.html.erb
<% provide(:title, 'Players in bet') %>
<h1>All players</h1>

<table class="players">
  <tr>
    <th>
      
    </th>
    
    <th>
      Player
    </th>
    <th>
      Pts
    </th>
    <th>
      Bets
    </th>
    <th>
      Predictions
    </th>
    <% if current_user.admin? %>
    <th>
    </th>
    <% end %>
  </tr>
  <% @players.each do |player| %>
    <%= render player %>
  <% end %>
</table>

<% if current_user.admin? %>
<div class = "adder-cont">
  <%= link_to "Add new player!", 'players/new', class: "btn adder btn-lg btn-primary" %>     
</div>
<% end %>
  

app/views/players/new.html.erb
<% provide(:title, 'Add player') %>
<h1>Add new player</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@player, html: { multipart: true }) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Create player", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/players/predictions.html.erb
<%= render "predictions/player_predictions" %>

app/views/players/show.html.erb
<% provide(:title, @player.name) %>
<div class="row">
  <aside class="col-md-4">
    <section >
      <h1>
        
        <%= @player.name %>
      </h1>
      <%= picture_for @player.picture.url, custom_size: true, 
                      cs: {:w => 120, :h => 80} %>
    </section>
    <div>
      <span>Points: </span> 
      <span class = "points"><%= @player.points %></span>
    </div>
    
    <section>
      <div>
        <div><%= link_to "Bets", player_bets_path(@player) %></div>
        <div><%= link_to "Predictions", player_predictions_path(@player) %></div>
      </div>
    </section>
  </aside>
  
  <% if current_user.admin? %>
  <aside class="col-md-4">
    <section>
          <div><%= link_to "edit", edit_player_path(@player) %></div>
    
          <div><%= link_to "delete", @player, method: :delete,
                                  data: { confirm: "You sure?" } %></div>
    </section>

  </aside>
  <% end %>

</div>