config/routes.rb
Rails.application.routes.draw do
  get 'teams/index'

  get 'teams/new'

  get 'teams/edit'

  get 'teams/show'

  get 'players/new'

  get 'session/new'

  get 'users/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'standings' => 'static_pages#standings'
  get 'bet-standings', to: 'static_pages#bets_standings', as: 'bet_standings'
  
  get 'signup'  => 'users#new'
  get 'players_new'  => 'players#new'
  get 'teams_new'  => 'teams#new'
  
  get '/users/:id/edit_admin_role', to: 'users#edit_admin_role', as: 'edit_admin_role_user'
  
  get '/players/:player_id/predictions/new', to: 'predictions#new', as: 'add_prediction_to_player'
  
  get '/players/:player_id/predictions', to: 'players#predictions', as: 'player_predictions'
  get '/players/:player_id/bets', to: 'players#bets', as: 'player_bets'
  
  get 'teams/standings', to: 'teams#standings', as: 'teams_standings'
  
  
  post 'teams/update_standings_ajax', to: 'teams#update_standings_ajax'
  post 'update_all_standings', to: 'static_pages#update_all_standings_ajax'

  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :users
  resources :players
  resources :teams
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :predictions

 

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Designed by gh0c
  </small>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "KLADARA", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "NBA standings", standings_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li> 
            <a href="<%= user_path current_user %>" class="header-avatar" 
            title = "<%= current_user.name %> - my profile">
              <%= avatar_for current_user, size:30 %>
            </a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <% if current_user.admin? %>
                <li>Ja sam admin</li>
              <% else %>
                <li>Ja nisam admin</li>
              <% end %>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_header1.html.erb
<header class="navbar upper navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "KLADARA", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          
          <li> 
            <a href="<%= user_path current_user %>" class="header-avatar" 
            title = "<%= current_user.name %> - my profile">
              <%= header_avatar_for current_user, size:30 %>
            </a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle user-admin-text" data-toggle="dropdown">
              
              <div>
                <span><%= current_user.name %></span>
              
                <b class="caret"></b>
              </div>
              <% if current_user.admin? %>
              <span class = "small-admin-notific">admin</span>
              <% end %>

            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_header2.html.erb
<header class="navbar lower">
  
  <div class="container">
    
    <nav>
      <ul class="nav nav-pills navbar-nav">
        
        <li><%= link_to "NBA standings", standings_path %></li>
        <% if logged_in? %>

          <% if current_user.admin? %>
            
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                
                Players <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "All players", players_path %></li>
                <li><%= link_to "Add player", "/players/new" %></li>
              </ul>
            </li>
            
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                
                Teams <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "All teams", teams_path %></li>
                <li><%= link_to "Add team", "/teams/new" %></li>
                <li><%= link_to "Standings", teams_standings_path %></li>
              </ul>
            </li>
            
          <% else %>
        
            <li><%= link_to "Players", players_path %></li>
            <li><%= link_to "Teams", teams_path %></li>
          <% end %>
          <li><%= link_to "Bet standings", 'bet-standings' %></li>
        <% end %>
        
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
 <body>
    <%= render 'layouts/header1' %>
    <%= render 'layouts/header2' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if (Rails.env.development? && logged_in? && current_user.admin?) %>
    </div>
  </body>
</html>